### ISSUE TITLE
Feature Request: Add HTML, CSS, and JavaScript Support

### ISSUE THREAD

**Issue by JC-Coder** [JC-Coder/startease#2]
**Description:**

I would like to request the addition of HTML, CSS, and JavaScript support to the project generated by StartEase.

**Comment by Toyin5** [comment]
Assign this to me pls.
Also is this project registered on hacktorberfest?

**Comment by JC-Coder** [comment]
it's assigned to you .

**Comment by JC-Coder** [comment]
@Toyin5 no update from you on this . if no update in 24 hour from now , it'll be reassigned
