### ISSUE TITLE
Feature Request: Add Prettier

### ISSUE THREAD

**Issue by CreedDE** [JC-Coder/startease#22]
I noticed on PR #17 that a lot of formatting was submitted that removed semicolons or changed from single quotes to double quotes.

I would suggest adding [prettier](https://prettier.io/) to the repo to sort out these issues and streamline the coding style.
Also, I see this as an opportunity to expand this CLI App with tools like Prettier, to either learn new tools or add their favorite tools to the project.

I'm open contributing to this

**Comment by JC-Coder** [comment]
okay great . thanks for the observation . i'm assinging this to you
