### ISSUE TITLE
config name typo

### ISSUE THREAD

**Issue by Emmo00** [JC-Coder/startease#50]
![image](https://github.com/JC-Coder/startease/assets/88244468/05498b25-1761-45c0-9aab-f2da9b95655a)

the prettier config file is named `. prettierre` instead of `.prettierrc`.

Would have made a PR for a fix, but I can't seem to find where you implemented the scaffolding for the formatting and linting config files.

**Comment by JC-Coder** [comment]
@Emmo00 please where is this ? 
kindly provide more details to enable me find and fix . thanks

**Comment by Emmo00** [comment]
Using settings:

- expressjs
- no database

I had to do it twice to confirm.

Is this enough info?

**Comment by JC-Coder** [comment]
Thanks , i have fixed this and will be updated in next version

**Comment by Emmo00** [comment]
I'd be glad if you show me how you did it 🤔
